import './style/globals.css';
import 'bootstrap/dist/css/bootstrap.css';
import BootstrapClient from './components/BootstrapClient';




export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}
      <BootstrapClient />
      </body>
    </html>
  )
}
